#
# EFI Boot Guard
#
# Copyright (c) Siemens AG, 2017
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

language: c

compiler:
  - gcc

sudo: required

install:
  - sudo apt-get install gcc-multilib gnu-efi libpci-dev libz-dev:i386
  - sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu xenial universe'
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends --target-release xenial libcmocka-dev

script:
  - autoreconf -fi
  - mkdir build-x86_64 && cd build-x86_64
  - ../configure
  - make check
  # Switch to 32-bit (libcmocka-dev can only be installed in one variant)
  - sudo apt-get install --no-install-recommends --target-release xenial libcmocka-dev:i386
  - mkdir ../build-i586 && cd ../build-i586
  - ../configure --with-gnuefi-lib-dir=/usr/lib32 CFLAGS=-m32 host_alias=i586-linux
  - make check
